autspacestest/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('autspacestest/admin/', admin.site.urls),
    path('autspacestest/', include("demo.urls")),
]

demo/urls.py
from django.urls import path
from .views import AboutPageView, AutismPageView, HomePageView, \
     ModeratePageView, MyStoriesPageView, ShareStoriesPageView, \
     ViewStoriesPageView, OverviewPageView, RegistrationPageView, \
     LogoutPageView

app_name = 'demo'

urlpatterns = [
    path("about", AboutPageView.as_view(), name="about"),
    path("autism", AutismPageView.as_view(), name="autism"),
    path("", HomePageView.as_view(), name="home"),
    path("moderate", ModeratePageView.as_view(), name="moderate"),
    path("mystories", MyStoriesPageView.as_view(), name="mystories"),
    path("viewstories", ViewStoriesPageView.as_view(), name="viewstories"),
    path("registration", RegistrationPageView.as_view(), name="registration"),
]
#    path("sharestories", ShareStoriesPageView.as_view(), name="sharestories"),
#    path("logout", LogoutPageView.as_view(), name="logout"),
#    path("overview", OverviewPageView.as_view(), name="overview"),

demo/models.py
from django.db import models

# Create your models here.

demo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView

class AboutPageView(TemplateView):
    template_name = "about.html"

class AutismPageView(TemplateView):
    template_name = "autism.html"

class HomePageView(TemplateView):
    template_name = "home.html"

class ModeratePageView(TemplateView):
    template_name = "moderate.html"

class MyStoriesPageView(TemplateView):
    template_name = "mystories.html"

class ShareStoriesPageView(TemplateView):
    template_name = "sharestories.html"

class ViewStoriesPageView(TemplateView):
    template_name = "viewstories.html"

class OverviewPageView(TemplateView):
    template_name = "overview.html"

class RegistrationPageView(TemplateView):
    template_name = "registration.html"

class LogoutPageView(TemplateView):
    template_name = "logout.html"


# def homePageView(request):
#     return HttpResponse("Hello, World!")

templates/autism.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
  <!--  Stylesheet-->

  <!-- Bootstrap CSS -->
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
  <!--Google Fonts-->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;1,300&display=swap"
        rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic" rel="stylesheet" type="text/css">
  <title>What Autism Is</title>
    <!--    Stylesheet-->
  <link href="{% static 'css/autism.css' %}" rel="stylesheet">
</head>
<body>
<!-- Navigation-->
<section id="navigation">
  {% include 'partials/navigation.html' %}
  <div class="container-fluid">
  {% block content %}

  </div>
</section>
<!--Contents-->
<section id="content">
  <div class="row mx-0 py-4">
    <div class="list-group col-lg-3 cotent-list" id="content-bar">
      <h5 class="list-group-item content-title">Contents</h5>
      <a class="list-group-item list-group-item-action  d-flex justify-content-between align-items-center"
         href="#about-autspaces">About Autism<span class="badge badge-pill"></span></a>
      <a class="list-group-item list-group-item-action  d-flex justify-content-between align-items-center"
         href="#platform-usage">About Sensory Processing<span class="badge badge-pill"></span></a>
    </div>

    <div class="about-content col-9" data-offset="0" data-spy="scroll" data-target="#content-bar"
         style="position: relative; height: 800px;overflow: auto; padding: 2% 8%">
      <div class="about-autism">
      <h5 class="text-info" id="about-autspaces"><em></em>About Autism</h5>
      <p>Autism affects the way people communicate and experience the world around them.</p>

      <p>Autism is a spectrum of developmental conditions, including Asperger’s Syndrome. Every autistic person is different. Some are able to learn, live and work independently, while many have learning differences or co-occurring health conditions that require specialist support.</p>

      <p>"It’s just the way I process the world, it can give me challenges, but it gives me great joy too. I wouldn’t
        be me without it!"</p>
      <em>Rhi, autistic adult</em>
     <a class="col-lg-12" href="https://www.autistica.org.uk/what-is-autism/what-is-autism" target="_blank" rel="noopener noreferrer" >
       <button class="btn btn-outline-dark float-right" type="button">Find Out More in Autistica</button>
   </a>
      </div>
            <div class="about-autism">
      <h5 class="text-info" id="platform-usage"><em></em>About Sensory Processing</h5>
      <p>Sensory processing refers to the ways that our brains and bodies receive, sort, and respond to our environment using our senses. You might have heard of the five senses: touch, sight, hearing, smell and taste.</p>
      <p>There are more senses than just these five. We also have a sense of our own body, we are moving it, and where it is in space. This sense is called proprioception. If you catch a ball or touch your nose, you are using proprioception.</p>

      <p>There are lots of different opinions about how many senses there are. Other senses include: a sense of balance (equilibriocpetion), a sense of hot and cold (thermoception), a sense of your heart beating (cardioception), and a sense of time passing (chromoception).</p>

      <p>A lot of autistic people (as many as 9/10 autistic people depending on the study) have sensory processing
        differences compared to non-autistic people. This means that they might respond to their environments differently. Sometimes this can cause extra challenges and create barriers for autistic peeople compared to non-existent people when they navigate environments which were not build with autistic people in mind. For example, you might find lights brighter, noises louder, or busy spaces more overwhelming compared to non-autistic people. You may also experience positive differences.</p>
           <a class="col-lg-12"
              href="https://www.autism.org.uk/advice-and-guidance/topics/sensory-differences/sensory-differences/all-audiences" target="_blank" rel="noopener noreferrer">
       <button class="btn btn-outline-dark float-right" type="button">Find Out More in National
         Autistic Society</button>
   </a>
    </div>
    </div>
  </div>

</section>

<!-- Footer-->
<footer id="footer">
  {% include 'partials/footer.html' %}
  <div class="row">

  {% endblock %}
  </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% include 'partials/jquery.html' %}
</body>
</html>

templates/confirmation.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

  <!-- Bootstrap CSS -->
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">

  <!--Google Fonts-->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;1,300&display=swap"
        rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic" rel="stylesheet" type="text/css">

  <!--  Stylesheet-->
  <link href="{% static '/css/confirmation_page.css' %}" rel="stylesheet">
  <title>View Stories</title>
</head>
<body>
{% include 'main/partials/navigation.html' %}

<section class="confirmation">
  <div class="confirmation-container">
    <div class="confirm_success">
      <h1 class="big-heading">
        Success!
      </h1>

      <p class="title-text">
        Thank you for sharing your experience.
      </p>
    </div>
 </div>
    <div class="what-now-section">
      <p class="section-heading">
        What happens now ?</p>
      <div class="what-now-text">
          <ul>
          <li><p class="text">
           If you chose to share your experience with the world, an autistic moderator
            will check that it follows our code of conduct, and if it does, you will receive a confirmation and your
              experience
            will then be published on this website.
          </p></li>

          <li><p class="text">
            If you chose to share it with researchers, it will be saved into a
            database, and researchers who follow
            our values will be able to use it for their research.
          </p></li>
            </ul>
      </div>
    </div>

    <div class="to-do-container">
      <p class="to-do-heading">
        What would you like to do next ?
      </p>

      <div class="btn-class">
        <a href="{% url 'main:upload' %}">
          <button class="btn btn-outline-primary btn-lg" type="button">Enter Another Experience</button>
        </a>

        <a href="{% url 'main:my_stories' %}">
          <button class="btn btn-outline-primary btn-lg" type="button">Go To My Stories</button>
        </a>

        <a href="{% url 'main:view_experiences' %}">
          <button class="btn btn-outline-primary btn-lg" type="button">View Other Stories</button>
        </a>

        <a href="{% url 'main:about_us' %}">
          <button class="btn btn-outline-primary btn-lg" type="button">Find Out More About AutSPACEs</button>
        </a>

      </div>
    </div>
  </div>

</section>
</div>
<!--Footer-->
<section id="footer">
  {% include 'main/partials/footer.html'%}
</section>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% include 'main/partials/jquery.html' %}

</html>

</html>

templates/header.html
<a href = "{% url 'autism' %}">autism</a>

templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
  <!-- Bootstrap CSS -->
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
  <!--Google Fonts-->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;1,300&display=swap"
        rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic" rel="stylesheet" type="text/css">
<!--    Stylesheet-->
  <link href="{% static 'css/home.css' %}" rel="stylesheet">
  <!-- Icon-->
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

  <title>AutSPACEs Landing Page</title>
  </head>

<body>
<!--Navigation-->
<section id="title">
<!--  Navigation-->
    {% include 'partials/navigation.html' %}
   <div class="container-fluid">
     <!--Introduction of AutSPACEs-->
    <div class="row intro">
      <div class="col-lg-6 text-left">
        <h1 class="big-heading">AutSPACEs</h1>
      </div>
    </div>

    <div class="row intro intro-text">
      <div class="col-lg-7">
        <h3 class="title-text">Makes environments better for autistic people by sharing stories about how senses
          affect
          people</h3>
         <a class="col-lg-12" href="{% url 'demo:about' %}">
       <button class="btn btn-outline-light btn-lg float-left" type="button">Read More</button>
   </a>

      </div>
      <div class="col-lg-5">
        <img class="title-image" src="{% static 'images/animation_a.jpg' %}" alt="Illustration" />
      </div>
    </div>
  </div>

</section>
<section id="value">
  <div class="row">
  <div class="col-lg-4 value-box">
     <h3 class="value-heading">Increase</h3>
  <p class="value-text">understanding of sensory processing</p>
  </div>

  <div class="col-lg-4 value-box">
  <h3 class="value-heading">Share</h3>
  <p class="value-text"> strategies and experiences of autistic people</p>
</div>

  <div class="col-lg-4 value-box">
  <h3 class="value-heading">Advise</h3>
  <p class="value-text">organisations how to create better environments for autistic people</p>
    </div>
    </div>
</section>
<!--How to Use the Platform-->
<section id="platform_usage">
  <div class="row">
      <div class="col-lg-12 platform-title">
      <h2 class="section-heading">How to Use The Platform</h2>
    </div>
  </div>
  <div class="row">
  <div class="col-lg-2 platform-box platform-left-border">
     <h3 class="usage-heading">Register<img class="usage-icon m-5"
                                            src="{% static "images/heart-fill.svg" %}" width="32"
          height="32"/ alt="Register" style="color: cornflowerblue;"></h3>
  </div>

  <div class="col-lg-2 platform-box">
  <h3 class="usage-heading">Share<img class="usage-icon m-5"
                                            src="{% static "images/send.svg" %}" width="32"
          height="32"/ alt="Register" style="color: cornflowerblue;"></h3>
</div>

  <div class="col-lg-2 platform-box">
  <h3 class="usage-heading">Choose<img class="usage-icon m-5"
                                            src="{% static "images/pie-chart-fill.svg" %}" width="32"
          height="32"/ alt="Register" style="color: cornflowerblue;"></h3>
    </div>

     <div class="col-lg-2 platform-box">
  <h3 class="usage-heading">Check<img class="usage-icon m-5"
                                            src="{% static "images/ui-checks.svg" %}" width="32"
          height="32"/ alt="Register" style="color: cornflowerblue;"></h3>
    </div>

     <div class="col-lg-2 platform-box">
  <h3 class="usage-heading">Change<img class="usage-icon m-5"
                                            src="{% static "images/pencil-square.svg" %}" width="32"
          height="32"/ alt="Register" style="color: cornflowerblue;"></h3>
    </div>
      <a class="col-lg-12" href="{{ auth_url }}">
       <button class="btn btn-outline-light btn-lg float-right platform-button" type="button">Read More</button>
   </a>
    </div>

</section>
<!--  View Experiences -->
<section id="experience">
  <div class="row">
      <div class="col-lg-6 shared-experience">
      <h2 class="section-heading">Shared Stories</h2>
  </div>
  <div id="experience-carousel" class="carousel slide" data-ride="false" data-interval="false">
    <ol class="carousel-indicators">
      <li data-target="#experience-carousel" data-slide-to="0" class="active"></li>
      <li data-target="#experience-carousel" data-slide-to="1"></li>
      <li data-target="#experience-carousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="row">
        <img class="experience-image float-left d-block w-50" src="{% static "images/animation_d.jpg" %}" width="150"
          height="325"/ alt="First slide">
        <div class="col-md-5">
        <h3 class="experience-heading">Eating in a Restaurant</h3>
        <p class="experience-content">...Waiting for the food felt like some kind of marathon and I just got so overwhelmed. But now that I’ve
          realised hunger exacerbates my sensory differences I know how to cope. I try to make sure I’ve eaten something before I go out and a while back I bought some earplugs which are great for small and bustling places.. </p>
        <em small class="experience-content">Sdy</em>
         </div>
          </div>
      </div>
      <div class="carousel-item">
                <div class="row">
         <img class="experience-image float-left d-block w-50" src="{% static "images/animation_b.jpg" %}" width="150"
                  height="325"/ alt="Second slide">
                          <div class="col-md-5">

         <h3 class="experience-heading">Ice cream</h3>
         <p class="experience-content">...Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
           et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo co.... </p>
        <em class="experience-content">Ali</em>
                          </div>
                  </div>
      </div>
      <div class="carousel-item">
        <div class="row">
         <img class="experience-image float-left d-block w-50" src="{% static "images/animation_c.jpg" %}"/
          width="150"
          height="325"  alt="Third slide">
          <div class="col-md-5">
         <h3 class="experience-heading">Traffic</h3>
        <p class="experience-content">...Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo co .. </p>
        <em class="experience-content">Jess</em>
            </div>
          </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#experience-carousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#experience-carousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
      <a class="col-lg-12" href="{% url 'demo:viewstories' %}">
       <button class="btn btn-outline-dark btn-lg float-right" type="button">View More</button>
   </a>
        </div>

</section>
<!-- Call to Action-->
<section id="cta">
  <h2 class="section-heading">Get Involved</h2>
     <div class="row">
       <div class="cta-card col-lg-3">
         <div class="card">
           <h3 class="card-header cta-header">Management</h3>
           <div class="card-body">
             <p class="card-text">Contribute to the GitHub repository.</p>
                <a href="https://github.com/alan-turing-institute/AutisticaCitizenScience" class="btn btn-primary">Contribute</a>
           </div>
         </div>
       </div>
              <div class="cta-card col-lg-3">
         <div class="card">
           <h3 class="card-header cta-header">Development</h3>
           <div class="card-body">
             <p class="card-text">Contribute to the GitHub repository.</p>
                <a href="https://github.com/alan-turing-institute/AutSPACEs" class="btn btn-primary">Contribute</a>
           </div>
         </div>
       </div>
              <div class="cta-card col-lg-3">
         <div class="card">
           <h3 class="card-header cta-header">Discussion</h3>
           <div class="card-body">
             <p class="card-text">Join us on our public Slack Channel.</p>
                <a href="https://slackin.openhumans.org" class="btn btn-primary">Join Us</a>
           </div>
         </div>
       </div>
              <div class="cta-card col-lg-3">
         <div class="card">
           <h3 class="card-header cta-header">Updates</h3>
           <div class="card-body">
             <p class="card-text">Subscribe to our monthly newsletter.</p>
                <a href="https://tinyletter.com/AutisticaTuringCitizenScience" class="btn btn-primary">Subscribe</a>
           </div>
         </div>
       </div>
     </div>

</section>
<!--  What Autism is-->
<section id="autism">
  <div class="row align-items-center">
    <div class="col-lg-6">
      <h2 class="section-heading">What Autism Is</h2>
    </div>
    <div class="col-lg-6">
      <h4 class="autism-text">Autistic people often have different sensory processing to people who are not autistic
        .</h4>
      <h4 class="autism-text">By collecting together lots of autistic people’s experiences, we can change spaces so
        that
        they are
        better for autistic people.</h4>
      <a class="col-lg-12" href="{% url 'demo:autism' %}">
       <button class="btn btn-outline-dark btn-lg float-right" type="button">View More</button>
   </a>
    </div>
  </div>
<!--  Direct to 'What Autism Is Page-->
</section>
<!--Footer-->
<footer id="footer">
  {% include 'partials/footer.html' %}
  <div class="row">
  </div>

</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% include 'partials/jquery.html' %}
</body>


</html>

templates/mystories.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block content %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

  <!-- Bootstrap CSS -->
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">

  <!--Google Fonts-->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;1,300&display=swap"
        rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic" rel="stylesheet" type="text/css">

  <!--  Stylesheet-->
  <link href="{% static 'css/mystories.css' %}" rel="stylesheet">
  <title>View Stories</title>
</head>

<body>
<section id="intro">
{% include 'partials/navigation.html' %}
</section>

<section id="mystory">
  <div class="story-container">
    <p class="big-heading">
      My Stories
    </p>
    <p class="intro-text">
      Welcome to your personal AutSPACEs page. Here you can:
    </p>

    <ul class="can_do">
      <li class="list-item">See the experiences you have saved and submitted.
      </li>
      <li class="list-item">Change sharing permissions for your experiences.
      </li>
    </ul>
  </div>

  <div class="story-dashboard">
    <p class="dashboard-heading">
      Stories Dashboard
    </p>

    <div class="row story-card-row">
      <div class="story-card col-lg-4">
        <div class="card">
          <h3 class="story-head card-header process">In Process</h3>
          <div class="card-body">
            <ul>
              <li class="list-item"><p class="card-text">Waiting:<span> 2 stories</span></p></li>
              <li class="list-item"><p class="card-text">Moderating:<span> 1 story</span></p></li>
              <li class="list-item"><p class="card-text">Re-moderating<span> 0 story</span></p></li>

            </ul>
          </div>
        </div>
      </div>
      <div class="story-card col-lg-4">
        <div class="card">
          <h3 class="story-head card-header submitted">Moderated</h3>
          <div class="card-body">
            <ul>
              <li class="list-item"><p class="card-text">Moderated:<span> 3 stories</span></p></li>
              <li class="list-item"><p class="card-text">Accepted:<span> 3 stories</span></p></li>
              <li class="list-item"><p class="card-text">Rejected:<span> 0 story</span></p></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="story-card col-lg-4 message-card">
        <div class="card">
          <h3 class="story-head card-header messages">Messages</h3>
          <div class="card-body">
            <ul>
              <li><p class="card-text">Your story<span>"Traffic Lights"</span> have been accepted.</p></li>
            </ul>
            <a
              class="btn btn-outline-info float-right view-btn"
              href="{% url 'demo:viewstories' %}" rel="noopener noreferrer"
              target="_blank">View Here
            </a>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>
<section id="story-table">
  <div class="story-table-container">
    <table class="table table-responsive-lg table-hover table-striped" style="width:auto">
      <thead>
      <tr>
        <th class="number-th" scope="col">Nr.</th>
        <th class="title-th" scope="col">Title</th>
        <th class="contributor-th" scope="col">Contributor</th>
        <th class="submission-date-th" scope="col">Submission Date</th>
        <th class="moderation-date-th" scope="col">Moderation Date</th>
        <th class="status-th" scope="col">Status</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Traffic Lights</td>
        <td>Self</td>
        <td>09-11-2021</td>
        <td>14-11-2021</td>
        <td>Accepted</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Taking subways in London</td>
        <td>For autistic friend</td>
        <td>09-11-2021</td>
        <td>14-11-2021</td>
        <td>Moderating</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Shopping in a market</td>
        <td>Self</td>
        <td>09-11-2021</td>
        <td>14-11-2021</td>
        <td>Re-moderating</td>
      </tr>
      </tbody>
    </table>
    <div class="contact-btn">
    <a
      class="btn btn-lg btn-outline-primary float-right"
      href="https://docs.google.com/forms/d/e/1FAIpQLSe_9MW3r4nsGUDxGWN24X88hqtz6q_347DC1gbMc_Yzj2Hrcg/viewform?fbzx=6470416391260718913" rel="noopener noreferrer"
      target="_blank">Contact Moderators
    </a>
      </div>
          </div>

</section>


<section id="footer">
  {% include 'partials/footer.html'%}
</section>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% include 'partials/jquery.html' %}

</html>
{% endblock %}

templates/partials/jquery.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

templates/partials/navigation.html
 {% load static %}
<!--    Stylesheet-->
  <link href="{% static 'css/navigation_light.css' %}" rel="stylesheet" id="mystylesheet">

  <div class="container-fluid nav-section">
  <nav class="navbar navbar-expand-xl navbar-dark">
      <a class="nav-content navbar-brand" href="#">AutSPACEs</a>
      <button aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
              data-target="#navbarText"
              data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav">
          <li>
          <a class="nav-content nav-item nav-link" href="{% url 'demo:home' %}">Home</a>
          </li>
          <li>
          <a class="nav-content nav-item nav-link" href="{% url 'demo:autism' %}">What Autism is</a>
          </li>
          {% if user.is_authenticated %}
             <li class="nav-item dropdown" style="padding: 0 0">
        <a class="nav-link dropdown-toggle nav-content" href="#" id="navbarDropdownMenuLink" role="button"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Experiences
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'demo:viewstories' %}">View Stories</a>
          <a class="dropdown-item" href="{% url 'demo:sharestories' %}">Share Stories</a>
          <a class="dropdown-item" href="{% url 'demo:moderate' %}">Moderate</a>
        </div>
      </li>
          <li>
          <a class="nav-content nav-item nav-link" href="{% url 'demo:mystories' %}">My Stories</a>
</li>
          {% else %}
          <li>
          <a class="nav-content nav-item nav-link" href="{% url 'demo:viewstories' %}">View Stories</a>
</li>
          {% endif %}
          <li>
          <a class="nav-content nav-item nav-link" href="{% url 'demo:about' %}">About Us</a>
          </li>
           <li>
          <a class="nav-content nav-item nav-link" href="{% url 'demo:moderate' %}">Moderate</a>
          </li>
           <li>
          <a class="nav-content nav-item nav-link" href="{% url 'demo:mystories' %}">My stories</a>
          </li>
           <li>
          <a class="nav-content nav-item nav-link" href="{% url 'demo:home' %}">THIS IS A TEST SITE ONLY</a>
          </li>
        </ul>
      </div>
<!--    <div class="btn-group btn-group-toggle" data-toggle="buttons">
      <label class="btn colorbutton active" style="background-color: #F9BB33">
        <input type="radio" name="options" id="option1" autocomplete="off" style="color: #F9BB33" checked>Color View
      </label>
      <label class="btn btn-outline-dark colorbutton">
        <input type="radio" name="options" id="option2" autocomplete="off">Calm View
      </label>
    </div>-->


      {% if user.is_authenticated %}
        <form action="{% url 'demo:logout' %}" method="post">{% csrf_token %}<input
            class="btn btn-light btn-lg"
                                                                                      type="submit" value="Log out">
          </form>
     {% elif not page_status == "registration" %}
        <a class="nav-content nav-item nav-link log-link" style="color: #fff" href="{{ auth_url }}">Log In</a>
      </a>
         <a href="{% url 'demo:registration' %}" class="nav-content nav-item btn btn-lg btn-light">Register</a>
      </a>
    {% endif %}

    </nav>
</div>

<!-- <script src="{% static 'js/colorswap.js' %}"></script>-->